
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR ID PLUS SEMICOLON STRINGprogram : expression SEMICOLON program\n               | expressionexpression : expression PLUS elementexpression : elementelement : IDelement : STRINGelement : CHAR'
    
_lr_action_items = {'ID':([0,7,8,],[4,4,4,]),'STRING':([0,7,8,],[5,5,5,]),'CHAR':([0,7,8,],[6,6,6,]),'$end':([1,2,3,4,5,6,9,10,],[0,-2,-4,-5,-6,-7,-1,-3,]),'SEMICOLON':([2,3,4,5,6,10,],[7,-4,-5,-6,-7,-3,]),'PLUS':([2,3,4,5,6,10,],[8,-4,-5,-6,-7,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,7,],[1,9,]),'expression':([0,7,],[2,2,]),'element':([0,7,8,],[3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> expression SEMICOLON program','program',3,'p_program','lab4.py',54),
  ('program -> expression','program',1,'p_program','lab4.py',55),
  ('expression -> expression PLUS element','expression',3,'p_expression_concat','lab4.py',62),
  ('expression -> element','expression',1,'p_expression_element','lab4.py',66),
  ('element -> ID','element',1,'p_element_id','lab4.py',70),
  ('element -> STRING','element',1,'p_element_string','lab4.py',74),
  ('element -> CHAR','element',1,'p_element_char','lab4.py',78),
]
