# Generated by Django 4.2.7 on 2023-12-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Выпечка',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=255)),
                ('Тип', models.CharField(max_length=50)),
                ('Стоимость', models.IntegerField()),
                ('Описание', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Клиент',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(max_length=255)),
                ('Адрес', models.CharField(max_length=255)),
                ('Телефон', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Пекарь',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(max_length=255)),
                ('Фамилия', models.CharField(max_length=255)),
                ('Контактный_Телефон', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Количество', models.IntegerField()),
                ('Сумма_Заказа', models.IntegerField()),
                ('Дата_Заказа', models.DateField()),
                ('Выпечка_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_app.выпечка')),
                ('Клиент_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_app.клиент')),
                ('Пекарь_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_app.пекарь')),
            ],
        ),
        migrations.CreateModel(
            name='Доставка',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Адрес_Доставки', models.CharField(max_length=255)),
                ('Дата_Доставки', models.DateField()),
                ('Статус_Доставки', models.CharField(max_length=50)),
                ('Заказ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_app.заказ')),
            ],
        ),
    ]
