# Generated by Django 4.2.7 on 2023-12-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_number', models.AutoField(primary_key=True, serialize=False, verbose_name='№БИБЛИОТЕКИ')),
                ('address', models.CharField(max_length=255, verbose_name='АДРЕС')),
                ('phone', models.CharField(max_length=15, verbose_name='ТЕЛЕФОН')),
            ],
            options={
                'verbose_name': 'БИБЛИОТЕКА',
                'verbose_name_plural': 'БИБЛИОТЕКИ',
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassSubject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
